PHONY := __all
__all:

# Do not use make's built-in rules and variables
# (this increases performance and avoids hard-to-debug behaviour)
MAKEFLAGS += -rR
MAKEFLAGS += --no-print-directory

CC		= $(CROSS_COMPILE)gcc
LD		= $(CROSS_COMPILE)ld
AR		= $(CROSS_COMPILE)ar
NM		= $(CROSS_COMPILE)nm
OBJCOPY		= $(CROSS_COMPILE)objcopy
OBJDUMP		= $(CROSS_COMPILE)objdump
READELF		= $(CROSS_COMPILE)readelf
STRIP		= $(CROSS_COMPILE)strip
LEX	        = flex
YACC        = bison

WAXINCLUDE = include/

LDFLAGS := -lcurl -lncurses
CFLAGS := -I$(WAXINCLUDE) -g

PHONY += all
__all: all FORCE
	@true # supress the print "Nothing to be done for '__all'"

ifeq ($(obj),)
  all: wax2
  obj-y += libwax/
  obj-y += core/
  obj-y += steam/
else
  all: $(obj)/built-in.o
  include $(obj)/Makefile
  obj-y := $(addprefix $(obj)/,$(obj-y))
  -include $(patsubst %.o,%.d,$(filter %.o,$(obj-y)))
endif

# strip all the '/' suffix for folder object
# depending on folder object is depending on the 'built-in.o' under the folder
obj-y := $(patsubst %/,%,$(obj-y))
obj-y := $(filter %.o,$(obj-y)) $(patsubst %,%/built-in.o,$(filter-out %.o,$(obj-y)))

# 'built-in.o' is depending on all the object 
# written in 'Makefile' under this folder
$(obj)/built-in.o: $(obj-y)
	@$(LD) -r -o $@ $^

%/built-in.o: % FORCE
	@$(MAKE) obj=$<

# Due to that the 'xxx.h' will become an prerequisites after including '%.d',
# so only take the first prerequisites by '$<'
%.o: %.c
	@printf "  %-7s %s\n" CC $@
	@$(CC) $(CFLAGS) -MMD -c -o $@ $<

%-yacc.c: %.y
	@printf "  %-7s %s\n" YACC $@
	@$(YACC) -H -o $@ $<

# If without NOTINTERMEDIATE target, make will treat 'foo.c' generated by 'foo.l'
# as intermediate files, after compiling, makefile will automatic remove it, that
# is so annoying, see https://www.gnu.org/software/make/manual/html_node/Chained-Rules.html
.NOTINTERMEDIATE:
%-lex.c: %.l
	@printf "  %-7s %s\n" LEX $@
	@$(LEX) -o $@ $<

rm-files += wax2 wax2_unstripped System.map
wax2: $(obj-y)
	@printf "  %-7s %s\n" LD $@_unstripped
	@$(CC) $(LDFLAGS) -o $@_unstripped $^

	@printf "  %-7s %s\n" NM System.map
	@$(NM) -n $@_unstripped > System.map

	@printf "  %-7s %s\n" STRIP $@
	@$(STRIP) -s -o $@ $@_unstripped

PHONY += clean
clean:
	@rm -vf $(rm-files)
	@find ./ -name "*.[od]" | xargs rm -vf
	@find ./ -name "*.l" | (while read i; do rm -vf $${i%%.l}-lex.c; done)
	@find ./ -name "*.y" | (while read i; do rm -vf $${i%%.y}-yacc.c $${i%%.y}-yacc.h; done)

PHONY += FORCE
FORCE:

.PHONY: $(PHONY)
